theme: jekyll-theme-cayman
title: Bring UserScript to Via Browser
header_btns: 
  - name: 讨论/反馈
    url: https://github.com/Xmader/Bring_UserScript_to_Via/issues
  - name: 安装
    url: javascript:install()
external_scripts:
  - https://cdn.jsdelivr.net/npm/sweetalert
  - dist/installer.js